Algoritmo "semnome"

Var


      numero, contador, salto: inteiro


Inicio

      Escreval("Deseja contar ate qual numero? ")
      leia(numero)
      Escreval("Qual o valor do salto? ")
      leia(salto)
      
      enquanto contador <= numero faca
               Escreval("conte: ", contador)
               
               contador <- contador + salto
      fimenquanto
      Escreval("terminei de contar")




Fimalgoritmo