Algoritmo "Atividade 5 - estrutura de repetição"


Var
       fatorial: inteiro
       numero: inteiro
       
       mult: real


Inicio


      mult <- 1
      Escreval("Qual fatorial deseja calcular?")
      leia(fatorial)
      
      para numero de 1 ate (fatorial) faca
      
           escreval("o fatorial eh: ", numero)
           
           escreval("")
           
           mult <- mult * numero
           
           escreval(mult)
      
      fimpara


Fimalgoritmo