Algoritmo "semnome"


Var

   nota: vetor[1..10] de real
   posicao: inteiro



Inicio

    Para posicao de 1 ate 10 passo 1 faca
      Escreval("Digite a nota do aluno: ")
      leia(nota[posicao])
    Fimpara

    Escreval("-----------------------------")

    para posicao de 1 ate 10 passo 1 faca
         escreval(nota[posicao])
    fimpara
    
    escreval("digite novamente a terceira nota do aluno: ")
    leia(nota[3])
    escreval(nota[3])

Fimalgoritmo